site_name: Keras.js Documentation
theme: readthedocs
repo_url: https://github.com/transcranial/keras-js
pages:
  - Home: index.md
  - Model Conversion: conversion.md
  - Setup:
    - Browser: setup/browser.md
    - Webpack: setup/webpack.md
    - Node.js: setup/node.md
  - Usage: usage.md
  - Caching: caching.md
  - Security: security.md
  - Architecture Diagrams: diagrams.md
  - Visualizations: visualizations.md
  - API:
    - Model: api/model.md
    - Tensor: api/tensor.md
    - Layer: api/layer.md
    - WebGL2: api/webgl2.md
  - Development: development.md
